Revert "don't use fixed paths"
If left unchanged this parameter causes MALMan to crash:
   File "/usr/lib/python2.7/logging/__init__.py", line 943, in _open
   stream = open(self.baseFilename, self.mode)
   IOError: [Errno 13] Permission denied: '/errors.log'
The config template should use sane default for the most common use case:
setting up a development environment.

This reverts commit bd10ba1588c20ca46a4f5f164ec55b2ce6e477f7.